devices([
  "iPhone 5",
  "iPhone 5s",
  "iPhone 6",
  "iPhone 6s",
])

languages([
  "en-US",
  "pt-BR"
])

app_identifier "com.rodrigo.belemdelivery"
scheme "BelemDeliveryFirebase"
configuration "Debug"
ios_version "9.3"
number_of_retries 2
reinstall_app true
stop_after_first_error true
clear_previous_screenshots true
